[package]
name = "campus-network-master"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"], default-features = false }
serde_json = { version="1.0", features = ["alloc"], default-features = false }
case= { version="1.0", default-features = false }